# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: database
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
        - 27017:27017

  mongo-express:
    container_name: database-dashboard
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: AddressProject.WebApi/Dockerfile
    restart: always
    ports:
      - 5000:5000
    environment:
      MongoDB__Host: mongo
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:3000
    depends_on:
      - backend